# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name ="titi",
    srcs = ["titi.cxx"],
    hdrs = ["titi.h"],
    visibility = ["//Detectors/MUON/MCH/Mapping/Toto:__pkg__"]
)