cc_library(
    name = "impl3",
    srcs = glob([
        "src/*.cxx",
        "src/*.h",
    ]),
    deps = [
        "//Detectors/MUON/MCH/Mapping/Interface:interface",
        "@boost//:format",
        "@boost//:geometry",
        "@ms_gsl//:gsl",
    ],
)
